import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-blue-600 text-white p-4">
          <div className="container mx-auto flex max-w-screen-xl justify-between items-center">
            {/* Logo */}
            <a href="#" className="text-xl font-bold">MySite</a>

            {/* Desktop Menu */}
            <div className="hidden md:flex space-x-6">
              <a href="#" className="hover:text-gray-200">Home</a>
              <a href="#" className="hover:text-gray-200">About</a>
              <a href="#" className="hover:text-gray-200">Services</a>
              <a href="#" className="hover:text-gray-200">Contact</a>
            </div>

            {/* Mobile Menu Button */}
            <button className="md:hidden flex items-center">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16m-7 6h7" />
              </svg>
            </button>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
